### ISSUE TITLE
error : 'gurobi_passthrough.h' file not found

### ISSUE THREAD

**Issue by zhumingpassional** [kwesiRutledge/goop2#1]
thanks for your valuable work.

I installed it ,and test the examples if this repo, but it raises errors.  could you pls tell me the reason? thanks  very much. 

github.com/kwesiRutledge/gurobi.go/gurobi
/usr/local/go/github.com/mit-drl/goop/solvers/gurobi/pkg/mod/github.com/kwesi!rutledge/gurobi.go@v0.0.0-20221111000100-e629c3f29605/gurobi/env.go:3:11: fatal error: 'gurobi_passthrough.h' file not found
 #include <gurobi_passthrough.h>
          ^~~~~~~~~~~~~~~~~~~~~~
1 error generated.

**Comment by kwesiRutledge** [comment]
Thanks for the question @zhumingpassional ! Although this repository is still available online, I've moved most of my work on Gurobi to [Gurobi.go](https://github.com/MatProGo-dev/Gurobi.go/tree/main) which I think you've found already.

I won't be maintaining `goop2` anymore and will probably archive it soon, but I will respond to questions about Gurobi.go!
